FROM node:12-buster

# Main microsoft repo
RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg && \
    mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/ && \
    wget -q https://packages.microsoft.com/config/debian/10/prod.list && \
    mv prod.list /etc/apt/sources.list.d/microsoft-prod.list && \
    chown root:root /etc/apt/trusted.gpg.d/microsoft.asc.gpg && \
    chown root:root /etc/apt/sources.list.d/microsoft-prod.list

# Azure CLI repo
RUN AZ_REPO=buster && \
    echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list

# Install tools
RUN apt-get update && \
    apt-get install -y apt-transport-https azure-functions-core-tools-3 azure-cli zsh lsb-release

ENV FUNCTIONS_CORE_TOOLS_TELEMETRY_OPTOUT=1